Update indentation, change loops, and remove unnecessary slash.

diff --git a/lmbench-regression b/lmbench-regression
--- a/lmbench-regression
+++ b/lmbench-regression
@@ -28,11 +28,13 @@ fi
 export ENOUGH TIMING_O LOOP_O
 
 if [ X$FILE = X ]
-then	FILE=/tmp/XXX
+then	
+	FILE=/tmp/XXX
 	touch $FILE || echo Can not create $FILE
 fi
 if [ X$MB = X ]
-then	MB=8
+then	
+	MB=8
 fi
 AVAILKB=`expr $MB \* 1024`
 
@@ -51,7 +53,8 @@ done
 
 
 if [ X$FSDIR = X ]
-then	FSDIR=/tmp/lat_fs
+then	
+	FSDIR=/tmp/lat_fs
 fi
 MP=N
 
@@ -91,26 +94,30 @@ echo \[VERSION: `uname -v`] 1>&2
 echo \[`date`] 1>&2
 echo \[`uptime`] 1>&2
 netstat -i | while read i
-do	echo \[net: "$i"] 1>&2
+do	
+	echo \[net: "$i"] 1>&2
 	set `echo $i`
 	case $1 in
 	    *ame)	;;
 	    *)		ifconfig $1 | while read i
-			do echo \[if: "$i"] 1>&2
+			do 
+				echo \[if: "$i"] 1>&2
 			done
 			;;
 	esac
 done
 
 mount | while read i
-do	echo \[mount: "$i"] 1>&2
+do	
+	echo \[mount: "$i"] 1>&2
 done
 
 STAT=$FSDIR/lmbench
 mkdir $FSDIR 2>/dev/null
 touch $STAT 2>/dev/null
 if [ ! -f $STAT ]
-then	echo "Can't make a file - $STAT - in $FSDIR"
+then	
+	echo "Can't make a file - $STAT - in $FSDIR"
 	touch $STAT
 	exit 1
 fi
@@ -137,15 +144,17 @@ function af_unix {
 # DP 7/4/18: This test intermittently hangs on SGX, taking out of CI for now
 #AF_UNIX
 	echo AF_UNIX socket latency
-	for i in $(eval echo "{1..$N_RUNS}")
-	do	run lat_unix
+	for i in `seq 1 $N_RUNS`
+	do	
+		run lat_unix
 	done
 }
 
 
 function wr_bw {
-	for i in $(eval echo "{1..$N_RUNS}")
-	do	rm -f $FILE
+	for i in `seq 1 $N_RUNS`
+	do	
+		rm -f $FILE
 		run lmdd label="File $FILE write bandwidth:" of=$FILE move=${MB}m fsync=1 print=3
 	done
 }
@@ -154,8 +163,9 @@ function udp_soc_lat {
 	echo UDP socket latency
 	run lat_udp -s &
 	sleep 3
-	for i in $(eval echo "{1..$N_RUNS}")
-	do	run lat_udp 127.0.0.1
+	for i in `seq 1 $N_RUNS`
+	do
+		run lat_udp 127.0.0.1
 		sleep 1
 	done
 	run lat_udp -127.0.0.1
@@ -166,8 +176,9 @@ function tcp_soc_lat {
 	echo TCP socket latency
 	run lat_tcp -s &
 	sleep 3
-	for i in $(eval echo "{1..$N_RUNS}")
-	do	run lat_tcp 127.0.0.1
+	for i in `seq 1 $N_RUNS`
+	do
+		run lat_tcp 127.0.0.1
 		sleep 1
 	done
 	run lat_tcp -127.0.0.1
@@ -188,8 +199,9 @@ function tcp_soc_bw {
 	echo TCP socket bandwidth
 	run bw_tcp -s &
 	sleep 3
-	for i in $(eval echo "{1..$N_RUNS}")
-	do	run bw_tcp 127.0.0.1
+	for i in `seq 1 $N_RUNS`
+	do
+		run bw_tcp 127.0.0.1
 		sleep 1
 	done
 	run bw_tcp -127.0.0.1
@@ -197,55 +209,57 @@ function tcp_soc_bw {
 }
 
 function bw_unix {
-	for i in $(eval echo "{1..$N_RUNS}")
-	do	run bw_unix
+	for i in `seq 1 $N_RUNS`
+	do
+		run bw_unix
 	done
 }
 
 function bw_pipe {
-	for i in $(eval echo "{1..$N_RUNS}")
-	do	run bw_pipe
+	for i in `seq 1 $N_RUNS`
+	do
+		run bw_pipe
 	done
 }
 
 
-declare -a tests=(\
-			"lat_syscall null" \
-			"lat_syscall read" \
-			"lat_syscall write" \
-			"lat_syscall stat $STAT" \
-			"lat_syscall fstat $STAT" \
-			"lat_syscall open $STAT" \
-			"lat_select file 500" \
+declare -a tests=(
+			"lat_syscall null"
+			"lat_syscall read"
+			"lat_syscall write"
+			"lat_syscall stat $STAT"
+			"lat_syscall fstat $STAT"
+			"lat_syscall open $STAT"
+			"lat_select file 500"
 # DP 1/20/18: This test intermittently hangs on SGX, taking out of CI for now
-#			"lat_select tcp 500" \
-			"lat_sig install" \
-			"lat_sig catch"	\
-			"lat_sig prot lat_sig" \
-			"lat_proc fork" \
+#			"lat_select tcp 500"
+			"lat_sig install"
+			"lat_sig catch"
+			"lat_sig prot lat_sig"
+			"lat_proc fork"
 ## DEP 6/16/18: Temporarily remove dfork from the unit tests
-#			"lat_proc dfork" \
+#			"lat_proc dfork"
 ## DEP 12/9/17: Temporarily remove vfork from the unit tests
-#			"lat_proc vfork" \
-		       "lat_proc exec" \
+#			"lat_proc vfork"
+			"lat_proc exec"
 ## DEP 6/19/18: Temporarily remove dforkexec from the unit tests
-#			"lat_proc dforkexec" \
+#			"lat_proc dforkexec"
 ## DEP 6/16/18: Temporarily remove shell from the unit tests
-#			"lat_proc shell" \
+#			"lat_proc shell"
 			"lat_fs $FSDIR"
 		);
 
-declare -a test_funcs=(\
+declare -a test_funcs=(
 # DP 7/4/18: This test intermittently hangs on SGX, taking out of CI for now
-#			"af_unix" \
-			"wr_bw" \
-			"udp_soc_lat" \
-			"tcp_soc_lat" \
-			"tcp_con_lat" \
-			"tcp_soc_bw" \
-			"bw_unix" \
+#			"af_unix"
+			"wr_bw"
+			"udp_soc_lat"
+			"tcp_soc_lat"
+			"tcp_con_lat"
+			"tcp_soc_bw"
+			"bw_unix"
 ## DEP 1/20/18: Temporarliy remove bw_pipe from the unit tests - intermittent hangs
-#			"bw_pipe" \
+#			"bw_pipe"
 		);
 
 date
@@ -254,15 +268,15 @@ msleep 250
 
 for i in `seq 0 $((${#tests[@]}-1))`
 do
-echo "Running ${tests[$i]}"
-run ${tests[$i]}
+	echo "Running ${tests[$i]}"
+	run ${tests[$i]}
 done
 
 
 for i in `seq 0 $((${#test_funcs[@]}-1))`
 do
-echo "Calling ${test_funcs[$i]}"
-${test_funcs[$i]}
+	echo "Calling ${test_funcs[$i]}"
+	${test_funcs[$i]}
 done
 
 rm -f /tmp/hello
